###
###  MINESTORE - Just Do Minecraft Donation
###        Created by JoraMelikyan
###             Adventures.Su
###

#Main settings
settings:
  #Enable mysql connection
  mysql:
    host: localhost
    port: 3306
    database: minestore
    username: store
    password: rdgm2020

#Create your own experience with MineStore
cart:
  #Cart title
  title: "&8(&cAdventures&8) &9Корзина покупок"

  #Rank item settings
  rank-name: "Привилегия"
  rank-lore:
    - "&aЭто корзина"
    - "вот так вот"
    - "Дата покупки: <date>"
    - "Цена: <price>"

  #Case item settings
  case-name: "Бокс"
  case-lore:
    - "Это корзина"
    - "вот так вот"

  #Money item settings
  money-name: "Токен"
  money-lore:
    - "Это корзина"
    - "вот так вот"